### PR TITLE
Introduces `VariableTermInterface`

### PR DESCRIPTION
**Pull request by mecha**
Attempts to incorporate a solution for #13

### CODE REVIEW

**Comment by XedinUnknown** [comment]
Are there any changes in `develop` that would break BC with `0.1`? If not, change `develop` alias to `0.1.x-dev`. BC-breaking changes can go into a `0.2` branch.

**Comment by mecha** [comment]
Yes. In `develop`, the context interfaces are no longer there and `ExpressionInterface` and `LogicalExpressisonInterface` no longer extend `EvaluableInterface`.

Didn't understand regarding putting BC-breaking changes into a `0.2` branch. The `develop` branch is already aliased as `0.2.x-dev`. Isn't this enough?

**Comment by XedinUnknown** [comment]
If `develop` gets aliased to `0.1.x-dev`, then it is no longer aliased to `0.2.x-dev`. For that, you will need a different branch.

**Comment by mecha** [comment]
Still don't understand. Why would `develop` get aliased to `0.1.x-dev` though?

**Comment by XedinUnknown** [comment]
The `develop` branch contains changes which break BC with `v0.1`. Leave branch alias as is.

**Pull request merged**
