### PR TITLE
Expression Type Standards

### PR DESCRIPTION
**Pull request by mecha**
Incorporates a solution for #10 by introducing interfaces with constants for common expression and term types.

### CODE REVIEW

**Review by XedinUnknown — CHANGES_REQUESTED** [review]
I like the changes proposed in this PR. However, I would like to see types standardized in general. This is what dhii/type-interface#1 aims to do. I think that these interfaces should implement that interface. I also think that the `validate()` method makes sense, and will be able to tell from the expression whether it is a valid expression of a given type.

Thoughts?

**Comment by mecha** [comment]
@XedinUnknown Ah yes, I forgot about those interfaces.

I agree that `validate()` can be a very powerful tool here. How about making these interfaces implement [`KeyAwareTypeInterface`](https://github.com/Dhii/type-interface/blob/task/initial-interfaces/src/KeyAwareTypeInterface.php)? These constants can be the standard for the keys returned by `KeyAwareTypeInterface#getType()`

Also, there is the [return type of `TermInterface#getType()`](https://github.com/Dhii/expression-interface/blob/develop/src/TermInterface.php#L19) to consider. It is currently documented as `string|Stringable`.

**Comment by XedinUnknown** [comment]
@mecha, sounds good WRT `KeyAwareTypeInterface`. I thought about making the type interfaces stringable. But I don't really like that idea: stringable is more of a utility, and IMHO not so suitable for representing concepts. However, the **expression** type can be made stringable perhaps, without forcing this onto other types. So, `ExpressionTypeInterface extends Stringable, KeyAwareTypeInterface`. Thoughts?

**Comment by XedinUnknown** [comment]
@mecha, why `TermTypeInterface` instead of `ExpressionTypeInterface`? Are some of those applicable to terms, but not to expressions?

**Comment by mecha** [comment]
@XedinUnknown It's not about applicability mostly. The type retrieval is declared in [`TermInterface`](https://github.com/Dhii/expression-interface/blob/task/10_expression-type-standard/src/TermInterface.php#L21). So for consistency's sake, I thought this would be more appropriate. Agree/disagree?

I understand that it might not make sense if you think about a "term" being a "leaf", but nothing in this package hints at that being the case. It is the base type for any object that can be part of an expression hierarchy.

**Review by XedinUnknown — APPROVED** [review]

**Pull request merged**
